[package]
name = "pet_os"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "src/kernel.rs"

[unstable]
# cross compile core library for custom target
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "i686.json"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
static_assertions = "1.1.0"
panic-halt = "0.2.0"
bitfield = "0.14.0"
bitflags = "2.3.3"
spin = "0.8.0" #newest version is not available for old archietectures
alloca = "0.3.4"