## The project target layout
- `target/loader/` ― the binary files of Dos loaders
  - Should be two files: `MBR.bin` and `OsLoader.bin`
- `target/apps` ― user defined (prebuilt) programs that will be available from the scratch
  - Files will be stored in `Programs` directory
- `target/kernel` ― should contain only one file `kernel.bin`
  - File will be initially bootstrap and loaded into real mode
  - Obviously, the file size should not exceed two MiB (the real mode restrictions)
- `target/images` ― holds bootable images of PetOS
  - At least, holds image.iso file that available to be run via CD-ROM
- `target/logs` ― the additional info about compilation process
  - Used by any compiler to save debug info