# With this file, another toolchain to the currently selected one will be used, when you execute `cargo build`.
# https://rust-lang.github.io/rustup/overrides.html

[toolchain]
channel = "nightly"
# equals to rust nightly 1.54 as of the release day 2021-05-10
targets = ["i686-unknown-linux-gnu"]
components = [ "rust-src", "rustc", "cargo", "rust-std", "clippy"]