# With this file, another toolchain to the currently selected one will be used, when you execute `cargo build`.
# https://rust-lang.github.io/rustup/overrides.html

[toolchain]
channel = "nightly-2025-02-13"

targets = ["i686-unknown-linux-gnu"]
components = [
    "rust-src",
    "rustc",
    "cargo",
    "rust-std",
    "clippy",
    "rust_analyzer",
]
