[build]
target = ["i686-unknown-linux-gnu"]
incremental = true

[target.i686-unknown-linux-gnu]
linker = "gcc"
rustflags = [
	"-C",
	"link-arg=-nostartfiles",
	"-C",
	"link-arg=-e",
	"-C",
	"link-arg=init",
]
